apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: iaf4ws38y-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/iaf4ws38y-dotnet-basic-gitops